# Setup
title:        TheAppFatory Blog
description:  Blog technologiczny
tagline:      Blog technologiczny
baseurl:      ""
paginate:     1
locale:       "pl"

# About/contact
author:
  name:       Mateusz Mytych
  url:        https://theappfactoryrepo.github.io 

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown
